apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-ts
  namespace: mdai
spec:
  variables:
    - key: loud_service_list
      serializeAs:
        - name: "LOUD_SERVICE_LIST"
          transformers:
            - type: join
              join:
                delimiter: ","
      dataType: set
    - key: super_loud_service_list
      serializeAs:
        - name: "SUPER_LOUD_SERVICE_LIST"
          transformers:
            - type: join
              join:
                delimiter: ","
      dataType: set

  prometheusAlert:
    - name: super_loud_services
      expr: 'sum(increase(trace_span_service_count_total{service_name!=""}[5m])) by (service_name) >= 1000'
      severity: warning
      for: 1m
      keep_firing_for: 1m
    - name: loud_services
      expr: '1000 > sum(increase(trace_span_service_count_total{service_name!=""}[5m])) by (service_name) >= 200'
      severity: warning
      for: 1m
      keep_firing_for: 1m

  automations:
    - eventRef: super_loud_services
      workflow:
        # remove the service from the other list first
        - handlerRef: HandleRemoveNoisyServiceFromSet
          args:
            payload_val_ref: service_name
            variable_ref: loud_service_list
        - handlerRef: HandleNoisyServiceAlert
          args:
            payload_val_ref: service_name
            variable_ref: super_loud_service_list
    - eventRef: loud_services
      workflow:
        # remove the service from the other list first
        - handlerRef: HandleRemoveNoisyServiceFromSet
          args:
            payload_val_ref: service_name
            variable_ref: super_loud_service_list
        - handlerRef: HandleNoisyServiceAlert
          args:
            payload_val_ref: service_name
            variable_ref: loud_service_list
