apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mydecisive.ai/hub-name: mdaihub-compliance
  name: gateway
  namespace: mdai
spec:
  managementState: managed
  image: otel/opentelemetry-collector-contrib:0.127.0
  replicas: 1
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  envFrom:
    - configMapRef:
        name: mdaihub-compliance-variables
  config:
    receivers:
      fluentforward:
        endpoint: "0.0.0.0:8006"

    extensions:
      health_check:
        endpoint: "${env:MY_POD_IP}:13133"

    processors:
      memory_limiter:
        check_interval: 23s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 1000
        send_batch_max_size: 10000
        timeout: 13s

    exporters:
      debug: {}

      debug/compliance:
        verbosity: detailed
        sampling_initial: 2
        sampling_thereafter: 100

    connectors:
      routing:
        table:
          - context: log
            condition: 'IsMatch(attributes["level"], "^(?i)(${env:NON_CRIT_LEVELS})$")'
            pipelines: [logs/filter]
          - context: log
            condition: 'IsMatch(attributes["level"], "^(?i)(${env:CRIT_LEVELS})$") or IsMatch(attributes["mdai_service"], "${env:CRIT_SERVICES}")'
            pipelines: [logs/compliance]

    service:
      telemetry:
        resource:
          mdai-logstream: collector
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: "0.0.0.0"
                    port: 8888
      extensions: [health_check]
      pipelines:
        logs/start:
          receivers: [fluentforward]
          processors: [memory_limiter, batch]
          exporters: [routing]

        logs/filter:
          receivers: [routing]
          exporters: [debug]

        logs/compliance:
          receivers: [routing]
          exporters: [debug/compliance]
