apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-sample
  namespace: mdai
spec:
  variables:
    - key: service_list
      serializeAs:
        - name: "SERVICE_LIST_REGEX"
          transformers:
            - type: join
              join:
                delimiter: "|"
        - name: "SERVICE_LIST_CSV"
          transformers:
            - type: join
              join:
                delimiter: ","
      # below properties are optional
      dataType: set
      storageType: "mdai-valkey"

  prometheusAlert:
    - name: top_talkers
      expr: 'sum(increase(bytes_received_by_service_total{mdai_service!=""}[1m])) by (mdai_service, data_type) > 800*1024'
      severity: warning
      for: 1m
      keep_firing_for: 1m
    - name: top_listeners
      expr: 'sum(increase(bytes_sent_by_service_total{mdai_service!=""}[1h])) by (mdai_service, data_type) > 10*1024*1024'
      severity: warning
      for: 15m
      keep_firing_for: 10m

  automations:
    - eventRef: top_talkers
      workflow:
        - handlerRef: HandleNoisyServiceAlert
          args:
            payload_val_ref: mdai_service
            variable_ref: service_list

  observers:
    - name: observer-in
      resourceRef: observer-collector
      labelResourceAttributes:
        - mdai_service
      countMetricName: items_received_by_service_total
      bytesMetricName: bytes_received_by_service_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'resource.attributes["observer_direction"] != "received"'
    - name: observer-out
      resourceRef: observer-collector
      labelResourceAttributes:
        - mdai_service
      countMetricName: items_sent_by_service_total
      bytesMetricName: bytes_sent_by_service_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'resource.attributes["observer_direction"] != "exported"'

  observerResources:
    - name: observer-collector
      image: public.ecr.aws/decisiveai/observer-collector:0.1
      ownLogsOtlpEndpoint: mdaihub-sample-observer-collector-service.mdai.svc.cluster.local:4318
      resources:
        limits:
          memory: "512Mi"
          cpu: "200m"
        requests:
          memory: "128Mi"
          cpu: "100m"