{
 "title": "MDAI Data Management",
 "description": "The MDAI Data Management dashboard shows the received and exported metrics for data running through MDAI, offering a high-level view of metrics for configured data being monitored and filtered via MDAI using MDAI Hub Custom Resource Configuration.",
 "tags": [ "mdai" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "receiverMetric",
    "label": "Receiver Metric",
    "query": {
     "query": "label_values({__name__=~\".+\", data_type!=\"\"}, __name__)"
    }
   },
   {
    "name": "receiverMetricByBytes",
    "label": "Receiver Metric by Bytes",
    "query": {
     "query": "label_values({__name__=~\".+\", data_type!=\"\"}, __name__)"
    }
   },
   {
    "name": "exporterMetric",
    "label": "Exporter Metric",
    "query": {
     "query": "label_values({__name__=~\".+\", data_type!=\"\"}, __name__)"
    }
   },
   {
    "name": "exporterMetricByBytes",
    "label": "Exporter Metric by Bytes",
    "query": {
     "query": "label_values({__name__=~\".+\", data_type!=\"\"}, __name__)"
    }
   },
   { "name": "dataType", "label": "Data Type", "query": "logs,metrics,traces" },
   { "name": "groupByLabel", "label": "Group By Label" }
  ]
 },
 "panels": [
  { "title": "Totals for I/O $dataType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MDAI Total by $groupByLabel",
   "type": "stat",
   "description": "Shows how many $groupByLabel monitored based on the current selected time interval.",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by($groupByLabel) (rate($receiverMetric{data_type=\"$dataType\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O $dataType",
   "type": "barchart",
   "description": "Total ingress and egress $dataType filtered through MDAI operator.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(sum by($groupByLabel) (increase($receiverMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum by($groupByLabel) (increase($exporterMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Percentage Difference I/O",
   "type": "gauge",
   "description": "Average percentage difference between ingress and egress $dataType.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase($receiverMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])) - sum(increase($exporterMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:]))",
     "legendFormat": "__auto"
    },
    { "expression": "$A * 100", "type": "math" }
   ]
  },
  { "title": "$dataType", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MDAI I/O by $groupByLabel",
   "type": "table",
   "description": "Total number of $dataType and size per service based on time interval for ingress and egress.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(\n  sum by ($groupByLabel) (increase($receiverMetric{data_type=\"$dataType\"}[$__rate_interval:])),\n  \"service\",\n  \"$1\",          \n  \"$groupByLabel\",\n  \"(.*)\"       \n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  sum by($groupByLabel) (increase($receiverMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])),\n  \"service\",\n  \"$1\",\n  \"$groupByLabel\",\n  \"(.*)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  sum by($groupByLabel) (increase($exporterMetric{data_type=\"$dataType\"}[$__rate_interval:])),\n  \"service\",\n  \"$1\",\n  \"$groupByLabel\",\n  \"(.*)\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  sum by($groupByLabel) (increase($exporterMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])),\n  \"service\",\n  \"$1\",\n  \"$groupByLabel\",\n  \"(.*)\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Talkers Recieved $dataType Totals",
   "type": "timeseries",
   "description": "Total number of $dataType from top talkers $groupByLabel ingested by MDAI",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(2, sum by($groupByLabel) (increase($receiverMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Talkers Sent $dataType Totals",
   "type": "timeseries",
   "description": "Total number of $dataType from top talkers $groupByLabel sent to configured destinations",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by($groupByLabel) (increase($exporterMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:]))\n  and on($groupByLabel)\ntopk(2, sum by($groupByLabel) (increase($receiverMetricByBytes{data_type=\"$dataType\"}[$__rate_interval:])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Active Filters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MDAI Active Filters for $dataType",
   "type": "alertlist",
   "description": "Current active filters for $dataType limiting egress of logs.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 }
  }
 ]
}