apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mdai
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "<YOUR_ID_HERE>"
  AWS_SECRET_ACCESS_KEY: <YOUR_SECRET_HERE>
---
apiVersion: hub.mydecisive.ai/v1
kind: MdaiCollector
metadata:
  namespace: mdai
  name: hub-monitor
spec:
  aws:
   awsAccessKeySecret: aws-credentials
  logs:
   s3:
     s3Region: "us-east-1"
     s3Bucket: "mdai-hub-logs"