apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: mdai
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: <secret-key-id-here> # DO NOT CHECK THIS IN TO SOURCE CONTROL
  AWS_SECRET_ACCESS_KEY: <secret-access-key-here> # DO NOT CHECK THIS IN TO SOURCE CONTROL
---
apiVersion: hub.mydecisive.ai/v1
kind: MdaiCollector
metadata:
  namespace: mdai
  name: hub-monitor
spec:
  aws:
   awsAccessKeySecret: aws-credentials
  logs:
   s3:
     s3Region: "us-east-1"
     s3Bucket: "mdai-audit-streams-0.8"