apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-compliance
  namespace: mdai
spec:
  variables:
    - key: bucket
      serializeAs:
        - name: "BUCKET_NAME"
      dataType: string
      storageType: "mdai-valkey"