
apiVersion: hub.mydecisive.ai/v1
kind: MdaiHub
metadata:
  labels:
    app.kubernetes.io/name: mdai-operator
    app.kubernetes.io/managed-by: kustomize
  name: mdaihub-df
  namespace: mdai
spec:
  variables:
    - key: service_list
      dataType: set
      serializeAs:
        - name: "SERVICE_LIST_REGEX"
          transformers:
            - type: join
              join:
                delimiter: "|"
      storageType: "mdai-valkey"
    - key: filter
      dataType: string
      serializeAs:
        - name: "FILTER"
      storageType: "mdai-valkey"
    - key: default
      dataType: string
      serializeAs:
        - name: "DEFAULT"
      storageType: "mdai-valkey"
    - key: severity_number
      dataType: int
      serializeAs:
        - name: "SEVERITY_NUMBER"
      storageType: "mdai-valkey"
    - key: any_service_alerted
      dataType: boolean
      serializeAs:
        - name: "SERVICE_ALERTED"
      storageType: "mdai-valkey"
    - key: attribute_map
      dataType: map
      serializeAs:
        - name: "ATTRIBUTES"
      storageType: "mdai-valkey"
    - key: severity_filters_by_level
      dataType: map
      serializeAs:
        - name: "SEVERITY_FILTERS_BY_LEVEL"
      storageType: "mdai-valkey"
    - key: my_priority_list
      type: meta
      dataType: metaPriorityList
      variableRefs:
        - default
        - service_list
      serializeAs:
        - name: "SERVICE_PRIORITY"
          transformers:
            - type: join
              join:
                delimiter: "|"
      storageType: "mdai-valkey"
    - key: my_hash_set
      type: meta
      dataType: metaHashSet
      variableRefs:
        - severity_number
        - severity_filters_by_level
      serializeAs:
        - name: "SERVICE_HASH_SET"
      storageType: "mdai-valkey"
  observers:
    - name: service-bytes-observer
      resourceRef: observer-collector
      labelResourceAttributes:
      - mdai_service
      - mdai_level
      - team
      - region
      countMetricName: mdai_observer_four_count_total
      bytesMetricName: mdai_observer_four_bytes_total
      filter:
        error_mode: ignore
        logs:
          log_record:
            - 'attributes["mdai_level"] == "INFO"'

  observerResources:
    - name: observer-collector
      image: public.ecr.aws/decisiveai/observer-collector:0.1

  prometheusAlert:
    - name: top_talkers
      expr: 'sum(increase(bytes_received_by_service_total{mdai_service!=""}[1m])) by (mdai_service, data_type) > 800*1024'
      severity: warning
      for: 1m
      keep_firing_for: 1m
    - name: top_listeners
      expr: 'sum(increase(bytes_sent_by_service_total{mdai_service!=""}[1h])) by (mdai_service, data_type) > 10*1024*1024'
      severity: warning
      for: 15m
      keep_firing_for: 10m

  automations:
    - eventRef: top_talkers
      workflow:
        - handlerRef: HandleNoisyServiceAlert
          args:
            payload_val_ref: mdai_service
            variable_ref: service_list