apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mydecisive.ai/hub-name: mdaihub-compliance
  name: gateway
  namespace: mdai
spec:
  managementState: managed
  image: otel/opentelemetry-collector-contrib:0.127.0
  replicas: 1
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  config:
    receivers:
      fluentforward:
        endpoint: "0.0.0.0:8006"

    extensions:
      health_check:
        endpoint: "${env:MY_POD_IP}:13133"

    processors:
      memory_limiter:
        check_interval: 23s
        limit_percentage: 75
        spike_limit_percentage: 15

      batch:
        send_batch_size: 1000
        send_batch_max_size: 10000
        timeout: 13s

      attributes/redact_pii_fields:
        actions:
          - key: email
            action: delete
          - key: phone
            action: delete
          - key: ssn
            action: delete
          - key: address
            action: delete

      transform/scrub_pii_fields:
        error_mode: propagate
        log_statements:
          - context: log
            statements:
              # Redact credit card numbers (keep last 4 digits)
              - ${env:CC_REPLACE_FN}

              # Redact email addresses (keep first 3 characters of username)
              - replace_pattern(attributes["email"], "\\b([a-zA-Z0-9._%+-]{3})[a-zA-Z0-9._%+-]*@([a-zA-Z0-9]{2})[a-zA-Z0-9.-]*\\.(\\w{2,})\\b", "$1***@$2**.***")

              # Redact phone numbers (keep last 4 digits)
              - replace_pattern(attributes["phone"], "\\b(?:\\+?1[-.\\s]?)?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?(\\d{4})\\b", "***-***-$1")

              # Redact address (keep first 4 digits)
              - replace_pattern(attributes["billing_address"], "\\b(\\d{1,5})\\s([\\w\\s]+),\\s([\\w\\s]+),\\s([A-Z]{2})\\s(\\d{5})\\b", "$1 **** REDACTED")

              # Redact SSN (keep last 4 digits)
              - replace_pattern(attributes["ssn"], "\\b\\d{3}-\\d{2}-(\\d{4})\\b", "***-**-$1")

              # Redact Name (fully redact name)
              - replace_pattern(attributes["name"], ".*", "***REDACTED****")

      attributes/hash_pii_fields:
        actions:
          - key: email
            action: hash
          - key: phone
            action: hash
          - key: ssn
            action: hash
          - key: address
            action: hash


    exporters:
      debug: {}

    service:
      telemetry:
        resource:
          mdai-logstream: collector
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: "0.0.0.0"
                    port: 8888
      extensions: [health_check]
      pipelines:
        logs/customer_pipeline:
          receivers: [fluentforward]
          processors: [memory_limiter, batch]
          exporters: [debug]
