apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mdaihub-name: mdaihub-compliance
  name: gateway
  namespace: mdai
spec:
  image: otel/opentelemetry-collector-contrib:0.117.0
  envFrom:
    - configMapRef:
        # this is the config map which will store your variables that your collector will use
        name: mdaihub-compliance-variables
  config:
    receivers:
      fluentforward:
        endpoint: '${env:MY_POD_IP}:8006'

    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check:
        endpoint: "${env:MY_POD_IP}:13133"

    processors:
      memory_limiter:
        check_interval: 23s
        limit_percentage: 75
        spike_limit_percentage: 15

      batch:
        send_batch_size: 10000
        timeout: 13s

      groupbyattrs:
        keys:
          - mdai_service

      resource/observer_receiver_tag:
        attributes:
          - key: observer_direction
            value: "received"
            action: upsert

      resource/observer_exporter_tag:
        attributes:
          - key: observer_direction
            value: "exported"
            action: upsert

      filter/non-essential-logs:
        error_mode: ignore
        logs:
          log_record:
            - 'IsMatch(attributes["level"], "INFO|DEBUG")'

    exporters:
      otlp/observer:
        endpoint: mdaihub-df-observer-collector-service.mdai.svc.cluster.local:4317
        tls:
          insecure: true

      awss3/compliance:
        marshaler: otlp_json
        s3uploader:
          region: us-east-1
          s3_bucket: mdai-compliance-logs
          s3_prefix: compliance-logs
          file_prefix: compliance-log_
          compression: gzip

    service:
      telemetry:
        metrics:
          address: ":8888"
      extensions:
        - health_check
      pipelines:
        logs/fluent:
          receivers: [ fluentforward ]
          processors: [ filter/non-essential-logs ]
          exporters: [ s3/compliance ]

        # the following pipelines are for observers
        logs/observer_receivers:
          # DO NOT change this connector without caution.
          # We add mdai_application in the logs/normalize pipeline.
          # This field is required for watching.
          # Pipeline logs/observer_receivers must be after normalization pipeline and before filtering occurs
          receivers: [ routing/filter ]
          processors: [
            resource/observer_receiver_tag,
            groupbyattrs,
            memory_limiter,
            # DO NOT CHANGE ORDER
            # batch must be last in processor list
            batch
          ]
          exporters: [ otlp/observer ]

        logs/observer_exporters:
          receivers: [ routing/external ]
          processors: [
            resource/observer_exporter_tag,
            groupbyattrs,
            memory_limiter,
            # DO NOT CHANGE ORDER
            # batch must be last in processor list
            batch,
          ]
          exporters: [ otlp/observer ]
