apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  labels:
    mdaihub-name: mdaihub-compliance
  name: gateway
  namespace: mdai
spec:
  managementState: managed
  image: otel/opentelemetry-collector-contrib:0.118.0
  replicas: 5
  resources:
    limits:
      memory: "256Mi"
      cpu: "200m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  envFrom:
    - configMapRef:
        # this is the config map which will store your variables that your collector will use
        name: mdaihub-compliance-variables
  config:
    receivers:
      fluentforward:
        endpoint: '${env:MY_POD_IP}:8006'

    extensions:
      # The health_check extension is mandatory for this chart.
      # Without the health_check extension the collector will fail the readiness and liveliness probes.
      # The health_check extension can be modified, but should never be removed.
      health_check:
        endpoint: "${env:MY_POD_IP}:13133"

    processors:
      memory_limiter:
        check_interval: 23s
        limit_percentage: 75
        spike_limit_percentage: 15

      batch:
        send_batch_size: 10000
        timeout: 13s

      groupbyattrs:
        keys:
          - level

      resource/observer_receiver_tag:
        attributes:
          - key: observer_direction
            value: "received"
            action: upsert

      resource/observer_exporter_tag:
        attributes:
          - key: observer_direction
            value: "exported"
            action: upsert

      filter/non-essential-logs:
        error_mode: ignore
        logs:
          log_record:
            - 'IsMatch(attributes["level"], "${env:LEVEL_REGEX}")'

    exporters:
      debug: { }

      otlp/observer:
        endpoint: mdaihub-compliance-observer-collector-service.mdai.svc.cluster.local:4317
        tls:
          insecure: true

      awss3/compliance:
        marshaler: otlp_json
        s3uploader:
          region: us-east-1
          s3_bucket: mdai-compliance-logs
          s3_prefix: compliance-logs
          file_prefix: compliance-log_
          compression: gzip

    service:
      telemetry:
        resource:
          mdai-logstream: collector
        logs:
          processors:
            - batch:
                exporter:
                  otlp:
                    protocol: http/protobuf
                    endpoint: http://hub-monitor-mdai-collector-service.mdai.svc.cluster.local:4318
        metrics:
          address: ":8888"
      extensions:
        - health_check
      pipelines:
        logs/fluent:
          receivers: [ fluentforward ]
          processors: [
            filter/non-essential-logs,
            # DO NOT CHANGE ORDER OF THE FOLLOWING PROCESSORS
            resource/observer_exporter_tag,
            groupbyattrs,
            memory_limiter,
            # DO NOT CHANGE ORDER
            # batch must be last in processor list
            batch,
          ]
          exporters: [ debug, s3/compliance ]

        logs/observer_exporters:
          receivers: [ fluentforward ]
          processors: [
            resource/observer_receiver_tag,
            groupbyattrs,
            memory_limiter,
            # DO NOT CHANGE ORDER
            # batch must be last in processor list
            batch,
          ]
          exporters: [ otlp/observer ]
