apiVersion: batch/v1
kind: CronJob
metadata:
  name: service-d-high-volume
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: telemetrygen
              image: public.ecr.aws/p3k6k6h3/telemetrygen:current
              imagePullPolicy: IfNotPresent
              args:
                - "traces"
                - "--otlp-endpoint"
                - "datadog-agent:4317"
                - "--otlp-insecure"
                - "true"
                - "--child-spans"
                - "3"
                - "--service"
                - "mdai-test-service-D"
                - "--span-duration"
                - "123ms"
                - "--traces"
                - "500"
                - "--telemetry-attributes"
                - "operation=\"high-volume-op\""
                - "--status-code"
                - "Ok"
          restartPolicy: OnFailure
