apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: gateway
  namespace: mdai
spec:
  mode: deployment
  image: otel/opentelemetry-collector-contrib:latest

  env:
    - name: AWS_S3_BUCKET
      valueFrom:
        configMapKeyRef:
          name: dal-collector-config
          key: AWS_S3_BUCKET
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          name: dal-collector-config
          key: AWS_REGION
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
          secretKeyRef:
            name: aws-credentials
            key: AWS_SECRET_ACCESS_KEY

  config:
    receivers:
      fluentforward:
        endpoint: "0.0.0.0:8006"
      otlp:
        protocols:
          http: {}
          grpc: {}

    processors:
      batch: {}

    exporters:
      awss3/metrics:
        s3uploader:
          region: ${env:AWS_REGION}
          disable_ssl: true
          s3_bucket: ${env:AWS_S3_BUCKET}
          s3_prefix: "metrics"
          s3_partition_format: "%Y/%m/%d/%H/%M"
          compression: gzip

      awss3/logs:
        s3uploader:
          region: ${env:AWS_REGION}
          disable_ssl: true
          s3_bucket: ${env:AWS_S3_BUCKET}
          s3_prefix: "logs"
          s3_partition_format: "%Y/%m/%d/%H/%M"
          compression: gzip

      awss3/traces:
        s3uploader:
          region: ${env:AWS_REGION}
          disable_ssl: true
          s3_bucket: ${env:AWS_S3_BUCKET}
          s3_prefix: "traces"
          s3_partition_format: "%Y/%m/%d/%H/%M"
          compression: gzip

      otlphttp/dal:
        endpoint: "http://mdai-dal-mdai-dal.default.svc.cluster.local:4318"
        tls:
          insecure: true
        # compression: "gzip"
        # timeout: 10s
        # sending_queue:
        #   enabled: true
        #   sizer: "items"
        #   num_consumers: 2
        #   queue_size: 100000
        #   batch:
        #     flush_timeout: 200ms
        #     min_size: 1000
        #     max_size: 10000

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/dal]

        logs:
          receivers: [otlp, fluentforward]
          processors: [batch]
          exporters: [otlphttp/dal]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/dal]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dal-collector-config
  namespace: mdai
data:
  AWS_S3_BUCKET: "mdai-test-dal"
  AWS_REGION: "us-east-1"

